### ISSUE TITLE
Dependency conflicts

### ISSUE THREAD

**Issue by danielbichuetti** [akhundMurad/typeid-python#14]
Would it be possible to remove the uuid6 version pin or update at least to the 2024 version? Some packages which support Python 3.12 have pinned to the 2024 version and some conflicts are up.

**Comment by akhundMurad** [comment]
Boa tarde @danielbichuetti !
I will include a fix in the next release (planned for the upcoming week).

**Comment by akhundMurad** [comment]
@danielbichuetti ready
