### ISSUE TITLE
0.3.0 spec support

### ISSUE THREAD

**Issue by iloveitaly** [akhundMurad/typeid-python#16]
Is this on the roadmap? Happy to contribute this if you are open to it.

**Comment by akhundMurad** [comment]
Hi, the latest spec is already supported

**Comment by iloveitaly** [comment]
Ah, interesting, this isn't clear from the typeid page. I'll submit a PR there to make it more clear. Thanks!

Curious, do you have any sample code/examples of how to use this with sqlalchemy or another ORM?

Thanks for all of your hard work here!

**Comment by akhundMurad** [comment]
@iloveitaly 
You check the examples folder to see integration with SQLALchemy.
Thanks for willing to support!
