### ISSUE TITLE
Inconsistencies in TypeID class

### ISSUE THREAD

**Issue by attevaltojarvi** [akhundMurad/typeid-python#9]
Hi, and thanks for this package!

I noticed a couple of inconsistencies in the TypeID class:

```
@classmethod
def from_uuid(cls, suffix: UUID, prefix: Optional[str] = None):
    suffix_str = _convert_uuid_to_b32(suffix)
    return TypeID(suffix=suffix_str, prefix=prefix)
```

this class method explicitly returns a `TypeID`, when it could use `cls`, like the `from_string` method right above it.

```
def _convert_b32_to_uuid(b32: str) -> UUID:
    return UUID(bytes=bytes(base32.decode(b32)))
```

I think this utility function should return the customized `uuid6.UUID` instead of `uuid.UUID`, since the class constructor calls `uuid6.uuid7()`. The difference is subtle, but this way the `.uuid` property can return incorrect results if you try to access `.uuid.time`:

```
uuid = uuid6.uuid7()
print(uuid.time)
>>> 1712728754957

tid = typeid.TypeID()
print(tid.uuid.time)
>>> 688659269629691542
```

`uuid6.UUID` has an overridden `time` property, which checks the `version`, and returns `super().time` if the version is not 6, 7, or 8.

The utility function could be updated like so:

```
def _convert_b32_to_uuid(b32: str):
    uuid_bytes = bytes(base32.decode(b32))
    uuid_int = int.from_bytes(uuid_bytes)
    return uuid6.UUID(int=uuid_int, version=7)
```

I ran into this while playing around with the idea of modifying the `uuid6.uuid7` generator function to receive the timestamp part as a parameter, so that I could also create TypeID instances based on some historical timestamp. This'd be a really useful feature when migrating from database-generated sequenced numeric IDs to TypeIDs. Some other ID generation libraries support this.

I can open a PR for these changes if you'd like. Thanks again!

**Comment by akhundMurad** [comment]
Hello @attevaltojarvi!
I appreciate your interest in TypeID.
Waiting for your PR 😁

**Comment by akhundMurad** [comment]
resolved by https://github.com/akhundMurad/typeid-python/pull/10
